### ISSUE TITLE
typo in widget reader selections

### ISSUE THREAD

**Issue by chrishavlin** [data-exp-lab/yt-napari#104]
Selection object names say "Selection Selection", see screenshot

![Screenshot from 2023-10-16 09-23-29](https://github.com/data-exp-lab/yt-napari/assets/22038879/8ce95cc9-c956-4a28-8b20-8f6867c0be5b)

**Comment by chrishavlin** [comment]
Yup, that's all.

**Comment by chrishavlin** [comment]
Though it's generated semi-dynamically, so not positive why it's being duplicated.

**Comment by TomasPetro** [comment]
Hi I've been a bit busy the last few weeks. I've been looking at the widget reader but I don't understand a bit where to edit the load_sample method since I don't see it in the file widget_reader. Tomas

**Comment by chrishavlin** [comment]
>  I've been looking at the widget reader but I don't understand a bit where to edit the load_sample method since I don't see it in the file widget_reader. 

Hi there, I think you responded to the wrong issue. I'll respond over in issue #92.
