### ISSUE TITLE
ds cacheing in dock widget

### ISSUE THREAD

**Issue by chrishavlin** [data-exp-lab/yt-napari#29]
The new widget (#27) is fairly minimal. One thing that would be good to add is some dataset cacheing -- right now every time the `load` button is hit, it will load the provded filename into a yt `ds`. Should be feasible to add a cache of that `ds` and selection objects as  attributes on the `ReaderWidget` so that subsequent loads do not need to rebuild those objects when just changing the field name. Would just need to watch for changes in the filename or selection parameters.

**Comment by matthewturk** [comment]
I think that this is a good idea, and one that may have applications beyond
Napari.  We did this once upon a time in yt, long long ago, but not in the
best way.
