### ISSUE TITLE
sample data

### ISSUE THREAD

**Issue by chrishavlin** [data-exp-lab/yt-napari#60]
napari has a built in menu option to load sample data that can be populated by plugins -- if the yt-napari were adjusted to also us `yt.load_sample` it should be straightforward to populate some yt samples in the load sample data. relevant napari docs here: https://napari.org/stable/plugins/contributions.html#contributions-sample-data

**Comment by matthewturk** [comment]
We ship a JSON file with yt, so it could potentially just be queried directly?

**Comment by chrishavlin** [comment]
Oooh, ya, good idea!

We'd need to limit it to cartesian datasets and pick a default field to load. but that could be done with a config json on the yt-napari side that gets joined to `sample_data_registry.json` to populate enabled samples.
