### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by goanpeca** [data-exp-lab/yt-napari#87]
Hello team!

Working on https://github.com/conda-forge/yt-napari-feedstock/pull/3 we found the following:

Packages found by source code inspection but not in the meta.yaml:
- packaging
- qtpy
- unyt

Packages found in the meta.yaml but not found by source code inspection:
- npe2

Could you update the dependencies for the next version so that it matches the current usage of libraries in the packages?

Cheers!

**Comment by chrishavlin** [comment]
hmm, `setup.cfg` has all the up to date requirements (and matches pypi for the latest release):

```
install_requires =
    magicgui>=0.6.1
    napari>=0.4.13
    numpy
    packaging
    pydantic
    qtpy
    unyt
    yt>=4.0.1
```

we have our dev requirements in a `requirements.txt`, could that be causing some confusion?

**Comment by goanpeca** [comment]
Hi 🔆, Its  ok I think the bot will search the source code, so if the tests are inside the src folder, they will be flagged as a dependency found, so we manually check that when the bot opens the PR just to be safe :)

**Comment by chrishavlin** [comment]
ah, ok, that makes sense then. I actually moved the tests to within the source directory recently, so that explains why that changed...
